name: Dis.scription database Migration

on:
  push:
    branches:
      - main  # Adjust this to match your production branch

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Prisma Migrate
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Set your DATABASE_URL in the repository's secrets
      run: npx prisma migrate deploy
